### ISSUE TITLE
Ps gui does not work (using folia)

### ISSUE THREAD

**Issue by YusakiDev** [getplusm/ProtectionsBlocks#1]
```
[12:36:48 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'ps gui' in t.me.p1azmer.engine.command.CommandRegister(protectionsblocks)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1028) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:435) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2289) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2249) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1639) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at t.me.p1azmer.engine.api.command.CommandResult.getArg(CommandResult.java:32) ~[PLAZMER-ENGINE-2.4.4.jar:?]
        at t.me.p1azmer.plugin.protectionblocks.commands.MenuCommand.onExecute(MenuCommand.java:46) ~[ProtectionBlocks-1.0.7.jar:?]
        at t.me.p1azmer.engine.api.command.AbstractCommand.execute(AbstractCommand.java:107) ~[PLAZMER-ENGINE-2.4.4.jar:?]
        at t.me.p1azmer.engine.api.command.GeneralCommand.onCommand(GeneralCommand.java:95) ~[PLAZMER-ENGINE-2.4.4.jar:?]
        at t.me.p1azmer.engine.command.CommandRegister.execute(CommandRegister.java:98) ~[PLAZMER-ENGINE-2.4.4.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 19 more
```

**Comment by YusakiDev** [comment]
also ps reload 

```
[12:44:02 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'ps reload' in t.me.p1azmer.engine.command.CommandRegister(protectionsblocks)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1028) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:435) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2289) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2249) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1639) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "t.me.p1azmer.folia.scheduling.ScheduledTask.taskId()" because the return value of "t.me.p1azmer.folia.Folia.executeTimer(java.lang.Runnable, long, long)" is null
        at t.me.p1azmer.engine.api.server.AbstractTask.start(AbstractTask.java:41) ~[PLAZMER-ENGINE-2.4.4.jar:?]
        at t.me.p1azmer.engine.api.data.AbstractDataHandler.onLoad(AbstractDataHandler.java:63) ~[PLAZMER-ENGINE-2.4.4.jar:?]
        at t.me.p1azmer.engine.api.data.AbstractUserDataHandler.onLoad(AbstractUserDataHandler.java:49) ~[PLAZMER-ENGINE-2.4.4.jar:?]
        at t.me.p1azmer.plugin.protectionblocks.data.DataHandler.onLoad(DataHandler.java:85) ~[ProtectionBlocks-1.0.7.jar:?]
        at t.me.p1azmer.engine.api.manager.AbstractManager.setup(AbstractManager.java:20) ~[PLAZMER-ENGINE-2.4.4.jar:?]
        at t.me.p1azmer.plugin.protectionblocks.ProtectionPlugin.setupDataHandlers(ProtectionPlugin.java:121) ~[ProtectionBlocks-1.0.7.jar:?]
        at t.me.p1azmer.engine.NexPlugin.loadManagers(NexPlugin.java:217) ~[PLAZMER-ENGINE-2.4.4.jar:?]
        at t.me.p1azmer.engine.NexPlugin.reload(NexPlugin.java:111) ~[PLAZMER-ENGINE-2.4.4.jar:?]
        at t.me.p1azmer.engine.command.list.ReloadSubCommand.onExecute(ReloadSubCommand.java:24) ~[PLAZMER-ENGINE-2.4.4.jar:?]
        at t.me.p1azmer.engine.api.command.AbstractCommand.execute(AbstractCommand.java:107) ~[PLAZMER-ENGINE-2.4.4.jar:?]
        at t.me.p1azmer.engine.api.command.GeneralCommand.onCommand(GeneralCommand.java:95) ~[PLAZMER-ENGINE-2.4.4.jar:?]
        at t.me.p1azmer.engine.command.CommandRegister.execute(CommandRegister.java:98) ~[PLAZMER-ENGINE-2.4.4.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 19 more
```
